// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADa1rDVLeg49zpjxyaKSm9IJcnTiOk4oo',
    appId: '1:983141739551:web:ef984cfd2bd8357ccaf92a',
    messagingSenderId: '983141739551',
    projectId: 'assesment-3-a0b02',
    authDomain: 'assesment-3-a0b02.firebaseapp.com',
    storageBucket: 'assesment-3-a0b02.firebasestorage.app',
    measurementId: 'G-4RQL27Q9J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9TCELiesFRAlLsfXG9EvUSrLwGk2Tsik',
    appId: '1:983141739551:android:cd308bc6549a9d8dcaf92a',
    messagingSenderId: '983141739551',
    projectId: 'assesment-3-a0b02',
    storageBucket: 'assesment-3-a0b02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4JZt9grKBS4lhnEvyQYkRzHeTTEewKLg',
    appId: '1:983141739551:ios:29c8ed31af0ff81acaf92a',
    messagingSenderId: '983141739551',
    projectId: 'assesment-3-a0b02',
    storageBucket: 'assesment-3-a0b02.firebasestorage.app',
    iosBundleId: 'com.example.assessment3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4JZt9grKBS4lhnEvyQYkRzHeTTEewKLg',
    appId: '1:983141739551:ios:29c8ed31af0ff81acaf92a',
    messagingSenderId: '983141739551',
    projectId: 'assesment-3-a0b02',
    storageBucket: 'assesment-3-a0b02.firebasestorage.app',
    iosBundleId: 'com.example.assessment3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADa1rDVLeg49zpjxyaKSm9IJcnTiOk4oo',
    appId: '1:983141739551:web:e8b4795690942c1ccaf92a',
    messagingSenderId: '983141739551',
    projectId: 'assesment-3-a0b02',
    authDomain: 'assesment-3-a0b02.firebaseapp.com',
    storageBucket: 'assesment-3-a0b02.firebasestorage.app',
    measurementId: 'G-P27028YZ9R',
  );
}
